root: true
extends: airbnb
rules:
  max-len: off
  no-console: off
  no-else-return: off
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  no-unexpected-multiline: error
  semi:
    - error
    - never
  require-jsdoc:
    - warn
plugins:
  - import
env:
  es6: true
  node: true